function prehrajDatum(den,mesic,rok)
    prehrajUvod(1);
    dmr=strcat(int2str(mesic),'-',int2str(den),'-',int2str(rok));
    [n, s] = weekday(dmr);
    n=n-1
    if(n==1)
        [Y,Fs,NBITS]=wavread('pondeli.wav');
        wavplay(Y,Fs);
    end
    if(n==2)
        [Y,Fs,NBITS]=wavread('utery.wav');
        wavplay(Y,Fs);
    end
    if(n==3)
        [Y,Fs,NBITS]=wavread('streda.wav');
        wavplay(Y,Fs);
    end
    if(n==4)
        [Y,Fs,NBITS]=wavread('ctvrtek.wav');
        wavplay(Y,Fs);
    end
    if(n==5)
        [Y,Fs,NBITS]=wavread('patek.wav');
        wavplay(Y,Fs);
    end
    if(n==6)
        [Y,Fs,NBITS]=wavread('sobota.wav');
        wavplay(Y,Fs);
    end
    if(n==7)
        [Y,Fs,NBITS]=wavread('nedele.wav');
        wavplay(Y,Fs);
    end
     
    prehrajCislo2pad(den);
    if(mesic==1)
        [Y,Fs,NBITS]=wavread('leden.wav');
        wavplay(Y,Fs);
    end   
    if(mesic==2)
        [Y,Fs,NBITS]=wavread('unor.wav');
        wavplay(Y,Fs);
    end
    if(mesic==3)
        [Y,Fs,NBITS]=wavread('brezen.wav');
        wavplay(Y,Fs);
    end
    if(mesic==4)
        [Y,Fs,NBITS]=wavread('duben.wav');
        wavplay(Y,Fs);
    end
    if(mesic==5)
        [Y,Fs,NBITS]=wavread('kveten.wav');
        wavplay(Y,Fs);
    end
    if(mesic==6)
        [Y,Fs,NBITS]=wavread('cerven.wav');
        wavplay(Y,Fs);
    end
    if(mesic==7)
        [Y,Fs,NBITS]=wavread('cervenec.wav');
        wavplay(Y,Fs);
    end
    if(mesic==8)
        [Y,Fs,NBITS]=wavread('srpen.wav');
        wavplay(Y,Fs);
    end
    if(mesic==9)
        [Y,Fs,NBITS]=wavread('zari.wav');
        wavplay(Y,Fs);
    end
    if(mesic==10)
        [Y,Fs,NBITS]=wavread('rijen.wav');
        wavplay(Y,Fs);
    end
    if(mesic==11)
        [Y,Fs,NBITS]=wavread('listopad.wav');
        wavplay(Y,Fs);
    end
    if(mesic==12)
        [Y,Fs,NBITS]=wavread('prosinec.wav');
        wavplay(Y,Fs);
    end
    if(mesic>12 || mesic<1)
        [Y,Fs,NBITS]=wavread('chyba.wav');
        wavplay(Y,Fs);
    end
end